trigger:
  branches:
    include:
      - main

variables:
- group: HomeManager

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
    echo "=== GIT STATUS ==="
    git status
    echo "=== GIT BRANCHES ==="
    git branch -a

    echo "Creating local main branch from origin/main..."
    git checkout -b main origin/main

    git config user.email "azuredevops@mirror"
    git config user.name "Azure DevOps Mirror Bot"

    echo "Adding GitHub remote..."
    git remote add github https://cjohn281:$(github_pat)@github.com/cjohn281/HomeManager_WEB.git
    
    echo "Pushing main branch to GitHub..."
    git push github main --force

    echo "Pushing tags to GitHub..."
    git push github --tags
  displayName: "Push main branch to GitHub"